### ISSUE TITLE
How to invoke GitHub Action from Allure Jobs

### ISSUE THREAD

**Issue by lxndrv** [allure-framework/allurectl#1]
Hi,
I have successfully imported test results from GitHub actions to Allure.
Now there is a requirement to invoke GitHub actions from Allure Jobs.
Is this functionality supported?    
The most close topic I found is: 
https://docs.qameta.io/allure-testops/integration/runjob-gitlab/
But admin/buildserver Type doesn't have an option for GitHub
Can you please assist or point to relevant documentation.
Thanks!

**Comment by cheshi-mantu** [comment]
> Hi,
> I have successfully imported test results from GitHub actions to Allure.
> Now there is a requirement to invoke GitHub actions from Allure Jobs.
> Is this functionality supported?
> The most close topic I found is:
> https://docs.qameta.io/allure-testops/integration/runjob-gitlab/
> But admin/buildserver Type doesn't have an option for GitHub
> Can you please assist or point to relevant documentation.
> Thanks!

Please follow the path: https://docs.qameta.io/allure-testops/integrations/github/main/
