### ISSUE TITLE
verstion 2.12.0 infinity watcher waiting

### ISSUE THREAD

**Issue by Paparama** [allure-framework/allurectl#15]
**Problem:**
When tests finish, watcher start processing files but can't finish it 
![telegram-cloud-photo-size-2-5377649575919209376-y](https://github.com/allure-framework/allurectl/assets/22013436/25cd3170-fbc1-4d59-b766-8d7184e01d8a)

**Script that using allurectl:**
    - ./allurectl watch -- npx cypress run --spec "$(node cypress/support/cypress-parallel.js)" --env allure=true,CI_JOB_URL=$CI_JOB_URL,NOTIFY=$NOTIFY,EXP_ID=$EXP_ID --browser chrome

**How to reproduce**
I don't know, because allurectl works fine with other projects (like pytest or earlgrey)
also I have parallel ci test jobs which using cypress and only 1 from 8 catch this problem

**How to fix**
Just use version 2.11

**Comment by cheshi-mantu** [comment]
@Paparama 
hi
please register all allurectl relates issues as described

<img width="834" alt="image" src="https://github.com/allure-framework/allurectl/assets/8607348/605fcc44-530c-49d2-88ab-5c3007fa8f29">

**Comment by cheshi-mantu** [comment]
wrong channel for the issue registration
