### ISSUE TITLE
Added method get Launch ID

### ISSUE THREAD

**Issue by VladislavIvanovQA** [allure-framework/allurectl#2]
Hi!
Please added method for get this launch id!

Example code
```
allurectl launch list --project-id=${ALLURE_PROJECT_ID} >> launchList.txt //Get list launch from Allure TestOps

cat launchList.txt | grep "${ALLURE_LAUNCH_NAME}" >> temp.txt //Search line for naming 

allure launch export LaunchId=$(awk '{print $1'} temp.txt) // get first column (ID) and export ENV
```

**Comment by cheshi-mantu** [comment]
hey!

> Hi!
> Please added method for get this launch id!
> 
> Example code
> 
> ```
> allurectl launch list --project-id=${ALLURE_PROJECT_ID} >> launchList.txt //Get list launch from Allure TestOps
> 
> cat launchList.txt | grep "${ALLURE_LAUNCH_NAME}" >> temp.txt //Search line for naming 
> 
> allure launch export LaunchId=$(awk '{print $1'} temp.txt) // get first column (ID) and export ENV
> ```

hey! you already have this data in your buikld job in the env vars.
add printenv to your CI and filter by 'ALLURE_'
you'll see
+ printenv
+ grep ALLURE_
ALLURE_JOB_RUN_ID=2171
ALLURE_LAUNCH_ID=2337
ALLURE_PROJECT_ID=118
ALLURE_EXECUTION_ID=2171

for future cases, please use support.qameta.io for Allure TestOps related issues

**Comment by eof151** [comment]
> hey!
> 
> > Hi!
> > Please added method for get this launch id!
> > Example code
> > ```
> > allurectl launch list --project-id=${ALLURE_PROJECT_ID} >> launchList.txt //Get list launch from Allure TestOps
> > 
> > cat launchList.txt | grep "${ALLURE_LAUNCH_NAME}" >> temp.txt //Search line for naming 
> > 
> > allure launch export LaunchId=$(awk '{print $1'} temp.txt) // get first column (ID) and export ENV
> > ```
> 
> hey! you already have this data in your buikld job in the env vars. add printenv to your CI and filter by 'ALLURE_' you'll see
> 
> * printenv
> * grep ALLURE_
>   ALLURE_JOB_RUN_ID=2171
>   ALLURE_LAUNCH_ID=2337
>   ALLURE_PROJECT_ID=118
>   ALLURE_EXECUTION_ID=2171
> 
> for future cases, please use support.qameta.io for Allure TestOps related issues

Hello! This is not working for GitLab (Allure 1.20.3), in "after_script" section the command "printenv" do not displays the ALLURE_LAUNCH_ID, ..JOB_RUN_ID, etc.

**Comment by Rotemsim3339** [comment]
Hi, so did you finally manage to get the ALLURE_LAUNCH_ID? and if so, how?

**Comment by cheshi-mantu** [comment]
allurectl is being reworked at this very moment and we'll release an updated version capable doing it

**Comment by cheshi-mantu** [comment]
export $(allurectl job-run env | grep ALLURE | xargs -L1)
ALLURE_LAUNCH_URL="${ALLURE_ENDPOINT}/launch/$ALLURE_LAUNCH_ID"
