### ISSUE TITLE
[BUG] directory-with-allure-results is unavailable if it's located on the second and lower levels

### ISSUE THREAD

**Issue by Zapevalov** [allure-framework/allurectl#3]
example:
we have such structure
```
rootDir
      |_src
      |_build
      |_./allurectl
      ...etc
```
execute commands
`$ export ALLURE_RESULTS=build/allure-results`
`$ ./allurectl_darwin_amd64 watch -- ./gradlew clean test`

and  after very long waiting we get the following log:
> 5 actionable tasks: 5 executed
> Test run finished, waiting for upload to finish...
> Waiting for all files to be indexed...
> We weren't able to index files during [5m]: found [17], indexed [0]
> Waiting for all files to be processed...
> All files have been processed: indexed [0], processed [0]

but, when directory-with-allure-results is located on the one level with app then there is no problems

**Comment by cheshi-mantu** [comment]
please

> example:
> we have such structure
> 
> ```
> rootDir
>       |_src
>       |_build
>       |_./allurectl
>       ...etc
> ```
> 
> execute commands
> `$ export ALLURE_RESULTS=build/allure-results`
> `$ ./allurectl_darwin_amd64 watch -- ./gradlew clean test`
> 
> and after very long waiting we get the following log:
> 
> > 5 actionable tasks: 5 executed
> > Test run finished, waiting for upload to finish...
> > Waiting for all files to be indexed...
> > We weren't able to index files during [5m]: found [17], indexed [0]
> > Waiting for all files to be processed...
> > All files have been processed: indexed [0], processed [0]
> 
> but, when directory-with-allure-results is located on the one level with app then there is no problems

please use support.qameta.io for the Allure TestOps related issues.
