### ISSUE TITLE
Feature request - optionally exit with status of watched process

### ISSUE THREAD

**Issue by sergeidyga** [allure-framework/allurectl#4]
`allurectl watch` exits with 0 both when child process exits with 0 or non-0.
For example:
`allurectl watch -- mvn test` will return 0 even when tests fail.
In CI process it might be desired to fail build or particular step in case of failed tests.
Proposal is to add flag that forces allurectl watch to return status code of child process or export it as a variable.

**Comment by cheshi-mantu** [comment]
added
