### ISSUE TITLE
auth to testops.cloud project fails.

### ISSUE THREAD

**Issue by markrity** [allure-framework/allurectl#6]
Hi, I'm trying to perform an auth to a fresh testops.cloud project.

`./allurectl auth login --endpoint "https://MYDOMAIN.testops.cloud" --token "MYTOKEN"`

Even though the token is correct and was just created I get the following output:
`2022/01/26 09:25:35 Can not auth by token POST : 404 Bad credentials`

Any suggestions how to connect to managed remote server?

**Comment by cheshi-mantu** [comment]
@markrity hi Mark
please use https://support.qameta.io for all the stuff related to Allure TestOps

**Comment by markrity** [comment]
@cheshi-mantu sure thanks.
