### ISSUE TITLE
Allure ctl watch stop uploading test results to allure server after an hour

### ISSUE THREAD

**Issue by mrnguyen4386** [allure-framework/allurectl#7]
Allure ctl watch stop uploading test results to allure server after an hour even though tests were still ongoing. I am not sure if I missed some parameters or something. I used the basic allure ctl watch parameters as follow:

$ export ALLURE_ENDPOINT=https://allure.company.com
$ export ALLURE_TOKEN=542dcd56-b0e2-4fdd-8ecf-bacf0f33d505
$ export ALLURE_PROJECT_ID=12
$ export ALLURE_LAUNCH_NAME="Hello, world"
$ export ALLURE_RESULTS=path/to/allure-results

I used help option which gave me more options but it's not very clear to me what they do and how they help with my issue.

**Comment by cheshi-mantu** [comment]
@mrnguyen4386 hi there
please report this to https://support.qameta.io using your corporate email for the registration
