### ISSUE TITLE
allurectl for windows trying to parse flags from tests run command

### ISSUE THREAD

**Issue by qwez** [allure-framework/allurectl#8]
`allurectl_windows_amd64.exe watch venv\Scripts\py.test.exe tests/test.py --alluredir=allure_result --endpoint <endpoint> --token <token> --project-id <id> --results allure_result --launch-name test_launch_3`
 Got error:
 `unknown flag: --alluredir`
But `--alluredir=allure_result` flag for pytest
How can I run watch if I need some flags to be passed to pytest?

**Comment by cheshi-mantu** [comment]
hi sir!
please check the documentation here: https://docs.qameta.io/allure-testops/ecosystem/allurectl/#allurectl-watch-workflow
your test invocation string is missing `--` before the `venv\Scripts\py.test.exe tests/test.py` string
the command must look like this: 
https://gitlab.com/cheshimantu/allure-pytest/-/blob/master/.gitlab-ci.yml#L25

**Comment by qwez** [comment]
hi
It helped, thanks.
I got confused by help on watch command:
`allurectl_windows_amd64.exe watch --help`
`Run test framework like allurectl watch 'mvn clean test'`

`Usage:`
`  allurectl watch '<cmd>' [flags]`
I think you should update help message

**Comment by cheshi-mantu** [comment]
@qwez hi sir, it's a generic rule for CLI apps to have the parameters supplied as `--param` or `-p`, but we'll explicitly add this. thanks for the suggestion.
